[package]
name = "nex5file-py"
version = "1.1.0"
edition = "2021"
description = "Python bindings for nex5file"
license = "MIT"

[lib]
name = "nex5file_py"
crate-type = ["cdylib"]

[dependencies]
nex5file = { path = "..", features = ["std"] }
pyo3 = { version = "0.23", features = ["extension-module"] }
